#!/bin/sh
# Regenerate agda-input-dump.tsv, the raw dump agda-input-escapes.json is
# derived from by hand -- see README.md, "The Unicode escape table".
set -e
curl -s -o agda-input.el https://raw.githubusercontent.com/agda/agda/master/src/data/emacs-mode/agda-input.el
curl -s -o latin-ltx.el  https://raw.githubusercontent.com/emacs-mirror/emacs/master/lisp/leim/quail/latin-ltx.el
emacs --batch --eval '(progn
  (load-file "agda-input.el")
  (agda-input-setup)
  (with-temp-buffer
    (dolist (pair (agda-input-get-translations "Agda"))
      (insert (format "%s\t%s\n" (car pair) (cdr pair))))
    (write-region (point-min) (point-max) "agda-input-dump.tsv")))'
